[package]
name = "pain-benchmarks-rust"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "fibonacci"
path = "fibonacci.rs"

[[bin]]
name = "factorial"
path = "factorial.rs"

[[bin]]
name = "sum"
path = "sum.rs"

